name = "TuringBenchmarking"
uuid = "0db1332d-5c25-4deb-809f-459bc696f94f"
authors = ["Tor Erlend Fjelde <tor.erlend95@gmail.com> and contributors"]
version = "0.5.4"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"

[extensions]
TuringBenchmarkingBridgeStanExt = "BridgeStan"

[compat]
ADTypes = "0.2, 1"
AbstractMCMC = "5"
BenchmarkTools = "1"
BridgeStan = "2"
DynamicPPL = "0.24.7, 0.25, 0.27, 0.28, 0.30"
ForwardDiff = "0.10.3"
LogDensityProblems = "2"
LogDensityProblemsAD = "1"
PrettyTables = "2"
Requires = "1"
ReverseDiff = "1.14"
Zygote = "0.6"
julia = "1.6"

[extras]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
